name: Build and deploy to gh-pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    env:
      ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      USER_NAME: Yisen
      USER_EMAIL: yisenliu@gmail.com
      PUBLISH_DIR: dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install and Build
        run: |
          yarn install
          yarn run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: 'gh-pages'
          folder: $PUBLISH_DIR
          token: $ACCESS_TOKEN
          git-config-name: $USER_NAME
          git-config-email: $USER_EMAIL
          commit-message: 'Deploy to gh-pages'
